- promises/README.md
#14 
This PR adds a comprehensive guide on **JavaScript Promises**. The guide explains the concept of promises in JavaScript, how to create them, and how to consume them with practical examples. It also covers various `Promise` API methods such as `Promise.all()`, `Promise.race()`, `Promise.any()`, and `Promise.allSettled()`.
The guide is located in a Markdown file named `Promises/README.md`.
- Added `promises-guide.md` containing the following sections:
- **Introduction to Promises**: Explanation of what promises are and their states.
- **Basic Syntax**: How to create and resolve/reject promises.
- **Consuming Promises**: Explanation of `.then()`, `.catch()`, and `.finally()`.
- **Chaining Promises**: Example of chaining multiple promises for sequential operations.
- **Promise API …
> [Add] JavaScript Promises Guide

- event-loop/README.md
> Added Event Loop In Javascript

- Async javascript/README.md
- Event Listeners/README.md
- Local and session storage/README.md
- README.md
- double equal and triple equal/README.md
- variable scoping/README.md
I had made the changes , and made a PR once please check and merge it into your main branch
> Important topics pr-no-24

- design-patterns/README.md
This PR adds well-documented implementations of several software design patterns in JavaScript. Each design pattern includes a detailed README and tests to showcase its use.
1. **Singleton Pattern** - Implements a class that restricts the instantiation to a single instance.
2. **Factory Pattern** - Provides a method to create objects without specifying the exact class of object that will be created.
3. **Observer Pattern** - Implements a way for multiple objects to observe and react to the changes in another object.
4. **Module Pattern** - Uses closures to create private/public encapsulation for objects.
5. **Adapter Pattern** - Allows incompatible interfaces to work together by wrapping an existing interface.
6. **Composite Pattern** - Composes objects into tree structures to represent …
> (Add) Design Patterns in Javascript Guide

- Array Methods/README.md
- README.md
issue no #11 
I have added js array methods
pls check once @neerajrathore
> Added js array methods

- README.md
- equality-comparison/README.md
- equality-comparison/deep_comparison.md
- equality-comparison/loose_vs_strict.md
- equality-comparison/object_comparison.md
for #12 issue
added this 
/equality_comparison/
│
├── README.md
├── loose_vs_strict.md
├── object_comparison.md
└── deep_comparison.md
also please add hacktoberfest , hacktoberfest-accepted label
> added Equality Comparison topic for 

- Arrays-Loops/README.md
- Arrays-Loops/Todo-project/README.md
- Arrays-Loops/arrays/README.md
- Arrays-Loops/loops/README.md
Closes #33
This PR adds a new section on JavaScript Arrays and Loops. The documentation includes:
- Detailed explanations of array properties and methods (e.g., .push(), .splice(), etc.)
- Different looping mechanisms (e.g., for, while)
- Practical examples demonstrating how to manipulate arrays with loops
Additionally, a simple Todo List project is included to help beginners understand how to use arrays and loops interactively, featuring functionalities like adding, removing, and rendering items with due dates.
> Added  Arrays and Loops with Todo List Project #33

- README.md
#54  added share on social media like twitter, linkedin, facebook.
> added share button

- property-flags-and-descriptors/README.md
I have added new topic in javascript-handbook: "Property Flags and Desctiptors"
please review and merge
> Added new topic: Property Flag and Descriptors

- array/index.html
- async-javascript/index.html
- class/index.html
- closure/index.html
- deep-shallow/index.html
- design-patterns/index.html
- double-equal-and-triple-equal/index.html
- equality-comparison/index.html
- event-listeners/index.html
- event-loop/index.html
- high-order-function/index.html
- hoisting/index.html
- index.html
- local-and-session-storage/index.html
- promise/index.html
- property-flags-and-descriptors/index.html
- prototype/index.html
- scripts.js
- styles.css
- try-catch/index.html
- var-let-const/index.html
- variable-scoping/index.html
solved issue #18 
before
https://github.com/user-attachments/assets/fce5988b-b7d3-4901-8bdc-4fc168f70fdf
after
https://github.com/user-attachments/assets/425cdf52-879c-4f44-becd-b1a29ef0bda5
> Changed ui of home page and page of every topic #18

- currying/README.md
- currying/examples/currying.js
- currying/examples/partial.js
- currying/examples/project.js
- currying/index.html
- currying/script.js
- currying/style.css
Issue: #65 
This PR adds a new topic to the JavaScript Handbook: **Currying in JavaScript**. It includes detailed explanations of currying, its usefulness, a comparison with partial application, and a simple project demonstrating its practical advantages.
1. **Topic Explanation:**
- **Why Is Currying in JavaScript Useful?**
- Explanation on how currying enhances code reusability and function composition.
- **Currying vs. Partial Application in JavaScript**
- A clear comparison between currying and partial application, highlighting the differences and use cases for each.
2. **Code Examples:**
- Demonstrations of basic currying and partial application.
- Practical examples, such as a **URL builder** using currying.
- A **Functional Discount Calculator** project that uses currying to apply …
> Currying in JavaScript

- index.html
- interview-questions/README.md
- interview-questions/index.html
this is in response to issue #51 and pr #61 
@neerajrathore I have made the changes u suggested.
pls check and if u merge add hacktoberfest-accepted label
also pls close pr #61 
Thanks!!!
> Added interview questions

- closure/README.md
- promise/README.md
Pull Request Preview
Title: Update README.md to Include Key Topics on Promises
Description:
This pull request updates the promise/Readme.md file by adding crucial topics that are essential for every JavaScript user to understand and implement in their work.
Changes Made:
Using Promises in Async/Await:
Introduced the concept of async/await syntax, which is built on top of promises. This section explains how it allows for cleaner and more readable code when dealing with asynchronous operations.
Using Promise.resolve() and Promise.reject():
Added information about the static methods Promise.resolve() and Promise.reject(). These methods are useful for quickly creating resolved or rejected promises, particularly in testing scenarios or when needing to enforce specific promise states.
This …
> #59 promises in Async_Await and resolve_reject

- README.md
- callback/README.md
- callback/index.html
- callback/script.js
- callback/style.css
Added JS Callback, Issue: #68 
This PR introduces an example demonstrating the use of async/await in JavaScript for handling asynchronous API requests. The implementation includes:
HTML: Basic structure with a button to trigger data fetch and a section to display results.
CSS: Simple styling for layout and button aesthetics.
JavaScript: Fetches data from an API using async/await, displays the result in the DOM, and handles potential errors.
This example improves readability and maintainability compared to traditional callback-based methods.
> [Hacktoberfest '24]: Added JS callback  (Issue: #68)

- styles.css
Corrected the margin and padding of the contact and share form
Fixes #74
> Correct margin and padding of contact and share

- .github/workflows/add-contributors.yml
- README.md
✅ Fixes: #80 
@neerajrathore This PR adds action workflow & simple markers too
This pull request introduces automation for updating the contributors list in the `README.md` file using a GitHub Actions workflow. The changes include adding a new workflow file and modifying the `README.md` to integrate with the action.
Automation for updating contributors:
* [`.github/workflows/add-contributors.yml`](diffhunk://#diff-4387a200be2fa409ad73ee2bf23884b607b1bc00d1b366aed9348b8726557423R1-R27): Added a new GitHub Actions workflow to automatically update the contributors list in the `README.md` file whenever there is a push to the `main` branch.
Modifications to `README.md`:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L51-R52): Replaced the …
> Add Action workflows for contributors

- destructuring-and-rest-spread/README.md
- destructuring-and-rest-spread/index.html
- index.html
Combined all issues into one PR ( #96 and #97 )
> Combined all commits into one

- index.html
- scripts.js
- styles.css
> Contact Us theme updated

- README.md
- document-object-model/README.md
- document-object-model/index.html
- index.html
New chapter on DOM is added
Fixes #109 
Kindly review my PR and add the `hacktoberfest-accepted` label to this @neerajrathore
> Added a new chapter

- call-bind-apply/README.md
- call-bind-apply/index.html
- index.html
Issue:- https://github.com/neerajrathore/javascript-handbook/issues/63
I created chapter on call(), apply(), and bind() methods under "Advanced Functions & Concepts".
Here is the output
https://github.com/user-attachments/assets/981896bb-fb9a-4dce-a400-a79ab3860241
> Added call-bind-apply folder ( with 1 commit)

- index.html
- scripts.js
- styles.css
Mobile-Only Navigation Menu for Improved Mobile Usability.
#104
> Nav bar responsive
